blank_issues_enabled: false
contact_links:
  - name: Discusiones de la comunidad
    url: "https://github.com/brayandiazc/github-profile-template-es/discussions"
    about: Haz preguntas generales o comparte tu perfil hecho con la plantilla
